// src/lib/localidadesArgentina.ts
// Localidades principales de Argentina con código postal de 4 dígitos
// Organizadas por provincia, ordenadas alfabéticamente

export interface Localidad {
  nombre: string;
  cp: string;
}

export const LOCALIDADES_POR_PROVINCIA: Record<string, Localidad[]> = {

  'Buenos Aires': [
    { nombre: 'Adrogué', cp: '1846' },
    { nombre: 'Avellaneda', cp: '1870' },
    { nombre: 'Azul', cp: '7300' },
    { nombre: 'Bahía Blanca', cp: '8000' },
    { nombre: 'Balcarce', cp: '7620' },
    { nombre: 'Banfield', cp: '1836' },
    { nombre: 'Berazategui', cp: '1884' },
    { nombre: 'Berisso', cp: '1935' },
    { nombre: 'Bernal', cp: '1876' },
    { nombre: 'Bolívar', cp: '6550' },
    { nombre: 'Burzaco', cp: '1852' },
    { nombre: 'Campana', cp: '6700' },
    { nombre: 'Cañuelas', cp: '1814' },
    { nombre: 'Castelar', cp: '1712' },
    { nombre: 'Chivilcoy', cp: '6620' },
    { nombre: 'Ciudadela', cp: '1702' },
    { nombre: 'Coronel Suárez', cp: '7540' },
    { nombre: 'Dolores', cp: '7100' },
    { nombre: 'Ensenada', cp: '1925' },
    { nombre: 'Ezeiza', cp: '1804' },
    { nombre: 'Florencio Varela', cp: '1888' },
    { nombre: 'General Rodríguez', cp: '1748' },
    { nombre: 'Glew', cp: '1856' },
    { nombre: 'González Catán', cp: '1759' },
    { nombre: 'Haedo', cp: '1706' },
    { nombre: 'Ituzaingó', cp: '1714' },
    { nombre: 'Junín', cp: '6000' },
    { nombre: 'La Plata', cp: '1900' },
    { nombre: 'Lanús', cp: '1824' },
    { nombre: 'Las Flores', cp: '7200' },
    { nombre: 'Lobos', cp: '7240' },
    { nombre: 'Lomas de Zamora', cp: '1832' },
    { nombre: 'Luján', cp: '6700' },
    { nombre: 'Mar del Plata', cp: '7600' },
    { nombre: 'Marcos Paz', cp: '1727' },
    { nombre: 'Mercedes', cp: '6600' },
    { nombre: 'Merlo', cp: '1722' },
    { nombre: 'Monte Grande', cp: '1842' },
    { nombre: 'Moreno', cp: '1744' },
    { nombre: 'Morón', cp: '1708' },
    { nombre: 'Necochea', cp: '7630' },
    { nombre: 'Nueve de Julio', cp: '6500' },
    { nombre: 'Olavarría', cp: '7400' },
    { nombre: 'Pehuajó', cp: '6450' },
    { nombre: 'Punta Alta', cp: '8109' },
    { nombre: 'Quilmes', cp: '1878' },
    { nombre: 'Ramos Mejía', cp: '1704' },
    { nombre: 'San Justo', cp: '1754' },
    { nombre: 'San Nicolás de los Arroyos', cp: '6550' },
    { nombre: 'San Pedro', cp: '6700' },
    { nombre: 'San Vicente', cp: '1865' },
    { nombre: 'Sarandí', cp: '1872' },
    { nombre: 'Tandil', cp: '7000' },
    { nombre: 'Temperley', cp: '1834' },
    { nombre: 'Trenque Lauquen', cp: '6400' },
    { nombre: 'Tres Arroyos', cp: '7500' },
    { nombre: 'Zárate', cp: '6700' },
  ],

  'Catamarca': [
    { nombre: 'Andalgalá', cp: '4740' },
    { nombre: 'Belén', cp: '4750' },
    { nombre: 'Fiambalá', cp: '4718' },
    { nombre: 'Hualfín', cp: '4753' },
    { nombre: 'Icaño', cp: '4728' },
    { nombre: 'Londres', cp: '4751' },
    { nombre: 'Pomán', cp: '4733' },
    { nombre: 'Recreo', cp: '4724' },
    { nombre: 'San Fernando del Valle de Catamarca', cp: '4700' },
    { nombre: 'Santa Rosa', cp: '4723' },
    { nombre: 'Tinogasta', cp: '4707' },
  ],

  'Chaco': [
    { nombre: 'Barranqueras', cp: '3503' },
    { nombre: 'Castelli', cp: '3518' },
    { nombre: 'Fontana', cp: '3514' },
    { nombre: 'General San Martín', cp: '3509' },
    { nombre: 'Machagai', cp: '3534' },
    { nombre: 'Presidencia de la Plaza', cp: '3536' },
    { nombre: 'Quitilipi', cp: '3530' },
    { nombre: 'Resistencia', cp: '3500' },
    { nombre: 'Villa Ángela', cp: '3540' },
  ],

  'Chubut': [
    { nombre: 'Comodoro Rivadavia', cp: '9000' },
    { nombre: 'Esquel', cp: '8820' },
    { nombre: 'Gaiman', cp: '8530' },
    { nombre: 'Puerto Madryn', cp: '8520' },
    { nombre: 'Rada Tilly', cp: '9001' },
    { nombre: 'Rawson', cp: '8503' },
    { nombre: 'Sarmiento', cp: '8837' },
    { nombre: 'Trelew', cp: '8500' },
    { nombre: 'Trevelin', cp: '8821' },
  ],

  'Ciudad Autónoma de Buenos Aires': [
    { nombre: 'Almagro', cp: '1194' },
    { nombre: 'Balvanera (Once)', cp: '1083' },
    { nombre: 'Barracas', cp: '1275' },
    { nombre: 'Belgrano', cp: '1426' },
    { nombre: 'Boedo', cp: '1239' },
    { nombre: 'Caballito', cp: '1405' },
    { nombre: 'Chacarita', cp: '1427' },
    { nombre: 'Coghlan', cp: '1430' },
    { nombre: 'Constitución', cp: '1254' },
    { nombre: 'Flores', cp: '1406' },
    { nombre: 'Floresta', cp: '1407' },
    { nombre: 'La Boca', cp: '1150' },
    { nombre: 'Liniers', cp: '1408' },
    { nombre: 'Mataderos', cp: '1440' },
    { nombre: 'Monserrat', cp: '1073' },
    { nombre: 'Núñez', cp: '1429' },
    { nombre: 'Palermo', cp: '1414' },
    { nombre: 'Parque Patricios', cp: '1266' },
    { nombre: 'Puerto Madero', cp: '1107' },
    { nombre: 'Recoleta', cp: '1425' },
    { nombre: 'Retiro', cp: '1001' },
    { nombre: 'Saavedra', cp: '1431' },
    { nombre: 'San Cristóbal', cp: '1212' },
    { nombre: 'San Nicolás', cp: '1035' },
    { nombre: 'San Telmo', cp: '1068' },
    { nombre: 'Villa Crespo', cp: '1414' },
    { nombre: 'Villa del Parque', cp: '1417' },
    { nombre: 'Villa Devoto', cp: '1417' },
    { nombre: 'Villa Lugano', cp: '1439' },
    { nombre: 'Villa Luro', cp: '1407' },
    { nombre: 'Villa Pueyrredón', cp: '1419' },
    { nombre: 'Villa Urquiza', cp: '1431' },
  ],

  'Córdoba': [
    { nombre: 'Alta Gracia', cp: '5186' },
    { nombre: 'Bell Ville', cp: '5270' },
    { nombre: 'Carlos Paz (Villa)', cp: '5152' },
    { nombre: 'Córdoba Capital', cp: '5000' },
    { nombre: 'Cosquín', cp: '5166' },
    { nombre: 'Cruz del Eje', cp: '5280' },
    { nombre: 'Deán Funes', cp: '5200' },
    { nombre: 'Jesús María', cp: '5220' },
    { nombre: 'La Calera', cp: '5151' },
    { nombre: 'La Falda', cp: '5172' },
    { nombre: 'Laboulaye', cp: '5200' },
    { nombre: 'Marcos Juárez', cp: '5282' },
    { nombre: 'Mina Clavero', cp: '5889' },
    { nombre: 'Río Ceballos', cp: '5111' },
    { nombre: 'Río Cuarto', cp: '5800' },
    { nombre: 'Río Tercero', cp: '5850' },
    { nombre: 'San Francisco', cp: '5100' },
    { nombre: 'Unquillo', cp: '5109' },
    { nombre: 'Villa Dolores', cp: '5870' },
    { nombre: 'Villa María', cp: '5900' },
  ],

  'Corrientes': [
    { nombre: 'Bella Vista', cp: '3432' },
    { nombre: 'Corrientes Capital', cp: '3400' },
    { nombre: 'Curuzú Cuatiá', cp: '3460' },
    { nombre: 'Esquina', cp: '3196' },
    { nombre: 'Goya', cp: '3450' },
    { nombre: 'Ituzaingó', cp: '3302' },
    { nombre: 'Mercedes', cp: '3470' },
    { nombre: 'Monte Caseros', cp: '3220' },
    { nombre: 'Paso de los Libres', cp: '3230' },
    { nombre: 'Santo Tomé', cp: '3340' },
  ],

  'Entre Ríos': [
    { nombre: 'Chajarí', cp: '3228' },
    { nombre: 'Colón', cp: '3280' },
    { nombre: 'Concepción del Uruguay', cp: '3260' },
    { nombre: 'Concordia', cp: '3200' },
    { nombre: 'Crespo', cp: '3116' },
    { nombre: 'Diamante', cp: '3105' },
    { nombre: 'Federación', cp: '3206' },
    { nombre: 'Gualeguay', cp: '3290' },
    { nombre: 'Gualeguaychú', cp: '3200' },
    { nombre: 'La Paz', cp: '3190' },
    { nombre: 'Nogoyá', cp: '3150' },
    { nombre: 'Paraná', cp: '3100' },
    { nombre: 'San José de Feliciano', cp: '3187' },
    { nombre: 'Victoria', cp: '3153' },
    { nombre: 'Villaguay', cp: '3240' },
  ],

  'Formosa': [
    { nombre: 'Clorinda', cp: '3610' },
    { nombre: 'Comandante Fontana', cp: '3620' },
    { nombre: 'El Colorado', cp: '3603' },
    { nombre: 'Formosa Capital', cp: '3600' },
    { nombre: 'General Belgrano', cp: '3613' },
    { nombre: 'Ibarreta', cp: '3624' },
    { nombre: 'Ingeniero Juárez', cp: '3636' },
    { nombre: 'Laguna Blanca', cp: '3604' },
    { nombre: 'Las Lomitas', cp: '3634' },
    { nombre: 'Pirané', cp: '3606' },
  ],

  'Jujuy': [
    { nombre: 'Abra Pampa', cp: '4640' },
    { nombre: 'El Carmen', cp: '4603' },
    { nombre: 'Fraile Pintado', cp: '4608' },
    { nombre: 'Humahuaca', cp: '4630' },
    { nombre: 'La Quiaca', cp: '4650' },
    { nombre: 'Ledesma (Libertador Gral. San Martín)', cp: '4512' },
    { nombre: 'Monterrico', cp: '4601' },
    { nombre: 'Palpalá', cp: '4612' },
    { nombre: 'Perico', cp: '4608' },
    { nombre: 'Purmamarca', cp: '4618' },
    { nombre: 'San Pedro de Jujuy', cp: '4500' },
    { nombre: 'San Salvador de Jujuy', cp: '4600' },
    { nombre: 'Tilcara', cp: '4624' },
  ],

  'La Pampa': [
    { nombre: 'Eduardo Castex', cp: '6380' },
    { nombre: 'General Acha', cp: '8200' },
    { nombre: 'General Pico', cp: '6360' },
    { nombre: 'Intendente Alvear', cp: '6309' },
    { nombre: 'Macachín', cp: '8307' },
    { nombre: 'Realicó', cp: '6200' },
    { nombre: 'Santa Rosa', cp: '6300' },
    { nombre: 'Toay', cp: '6303' },
    { nombre: 'Trenel', cp: '6363' },
    { nombre: 'Victorica', cp: '6319' },
    { nombre: 'Winifreda', cp: '6313' },
  ],

  'La Rioja': [
    { nombre: 'Aimogasta', cp: '5310' },
    { nombre: 'Chamical', cp: '5380' },
    { nombre: 'Chepes', cp: '5397' },
    { nombre: 'Chilecito', cp: '5360' },
    { nombre: 'Famatina', cp: '5365' },
    { nombre: 'La Rioja Capital', cp: '5300' },
    { nombre: 'Nonogasta', cp: '5361' },
    { nombre: 'Villa Unión', cp: '5350' },
  ],

  'Mendoza': [
    { nombre: 'General Alvear', cp: '5620' },
    { nombre: 'Godoy Cruz', cp: '5501' },
    { nombre: 'Guaymallén', cp: '5521' },
    { nombre: 'Junín', cp: '5573' },
    { nombre: 'Las Heras', cp: '5539' },
    { nombre: 'Lavalle', cp: '5533' },
    { nombre: 'Luján de Cuyo', cp: '5507' },
    { nombre: 'Maipú', cp: '5515' },
    { nombre: 'Malargüe', cp: '5613' },
    { nombre: 'Mendoza Capital', cp: '5500' },
    { nombre: 'Rivadavia', cp: '5577' },
    { nombre: 'San Martín', cp: '5570' },
    { nombre: 'San Rafael', cp: '5600' },
    { nombre: 'Tunuyán', cp: '5560' },
    { nombre: 'Tupungato', cp: '5561' },
  ],

  'Misiones': [
    { nombre: 'Apóstoles', cp: '3350' },
    { nombre: 'Candelaria', cp: '3308' },
    { nombre: 'Eldorado', cp: '3380' },
    { nombre: 'Garupá', cp: '3304' },
    { nombre: 'Jardín América', cp: '3328' },
    { nombre: 'Leandro N. Alem', cp: '3315' },
    { nombre: 'Montecarlo', cp: '3384' },
    { nombre: 'Oberá', cp: '3360' },
    { nombre: 'Posadas', cp: '3300' },
    { nombre: 'Puerto Iguazú', cp: '3370' },
    { nombre: 'Puerto Rico', cp: '3334' },
    { nombre: 'San Vicente', cp: '3364' },
    { nombre: 'Wanda', cp: '3376' },
  ],

  'Neuquén': [
    { nombre: 'Centenario', cp: '8309' },
    { nombre: 'Chos Malal', cp: '8353' },
    { nombre: 'Cutral Có', cp: '8322' },
    { nombre: 'Junín de los Andes', cp: '8371' },
    { nombre: 'Neuquén Capital', cp: '8300' },
    { nombre: 'Plaza Huincul', cp: '8318' },
    { nombre: 'Plottier', cp: '8316' },
    { nombre: 'San Martín de los Andes', cp: '8370' },
    { nombre: 'Senillosa', cp: '8311' },
    { nombre: 'Villa La Angostura', cp: '8407' },
    { nombre: 'Zapala', cp: '8340' },
  ],

  'Río Negro': [
    { nombre: 'Allen', cp: '8328' },
    { nombre: 'Bariloche (San Carlos de)', cp: '8400' },
    { nombre: 'Choele Choel', cp: '8360' },
    { nombre: 'Cipolletti', cp: '8324' },
    { nombre: 'El Bolsón', cp: '8430' },
    { nombre: 'General Roca', cp: '8332' },
    { nombre: 'Ingeniero Huergo', cp: '8334' },
    { nombre: 'Lamarque', cp: '8363' },
    { nombre: 'Luis Beltrán', cp: '8361' },
    { nombre: 'Sierra Grande', cp: '8468' },
    { nombre: 'Viedma', cp: '8500' },
    { nombre: 'Villa Regina', cp: '8336' },
  ],

  'Salta': [
    { nombre: 'Cafayate', cp: '4427' },
    { nombre: 'Cerrillos', cp: '4403' },
    { nombre: 'General Güemes', cp: '4430' },
    { nombre: 'Joaquín V. González', cp: '4448' },
    { nombre: 'La Caldera', cp: '4407' },
    { nombre: 'Metán', cp: '4440' },
    { nombre: 'Orán', cp: '4530' },
    { nombre: 'Rosario de la Frontera', cp: '4190' },
    { nombre: 'Rosario de Lerma', cp: '4405' },
    { nombre: 'Salta Capital', cp: '4400' },
    { nombre: 'San Lorenzo', cp: '4401' },
    { nombre: 'San Ramón de la Nueva Orán', cp: '4530' },
    { nombre: 'Tartagal', cp: '4560' },
    { nombre: 'Vaqueros', cp: '4401' },
  ],

  'San Juan': [
    { nombre: 'Albardón', cp: '5419' },
    { nombre: 'Barreal', cp: '5405' },
    { nombre: 'Calingasta', cp: '5403' },
    { nombre: 'Caucete', cp: '5442' },
    { nombre: 'Chimbas', cp: '5413' },
    { nombre: 'Jáchal', cp: '5460' },
    { nombre: 'Pocito', cp: '5427' },
    { nombre: 'Rawson', cp: '5425' },
    { nombre: 'Rivadavia', cp: '5423' },
    { nombre: 'San José de Jáchal', cp: '5460' },
    { nombre: 'San Juan Capital', cp: '5400' },
    { nombre: 'Santa Lucía', cp: '5411' },
    { nombre: 'Valle Fértil', cp: '5449' },
  ],

  'San Luis': [
    { nombre: 'Concarán', cp: '5770' },
    { nombre: 'Juana Koslay', cp: '5701' },
    { nombre: 'La Punta', cp: '5710' },
    { nombre: 'La Toma', cp: '5770' },
    { nombre: 'Merlo', cp: '5881' },
    { nombre: 'Naschel', cp: '5759' },
    { nombre: 'Potrero de los Funes', cp: '5701' },
    { nombre: 'San Luis Capital', cp: '5700' },
    { nombre: 'Santa Rosa del Conlara', cp: '5773' },
    { nombre: 'Tilisarao', cp: '5773' },
    { nombre: 'Villa Mercedes', cp: '5730' },
  ],

  'Santa Cruz': [
    { nombre: 'Caleta Olivia', cp: '9011' },
    { nombre: 'El Calafate', cp: '9405' },
    { nombre: 'El Chaltén', cp: '9301' },
    { nombre: 'Gobernador Gregores', cp: '9311' },
    { nombre: 'Las Heras', cp: '9017' },
    { nombre: 'Los Antiguos', cp: '9041' },
    { nombre: 'Perito Moreno', cp: '9040' },
    { nombre: 'Pico Truncado', cp: '9015' },
    { nombre: 'Puerto Deseado', cp: '9050' },
    { nombre: 'Puerto San Julián', cp: '9310' },
    { nombre: 'Puerto Santa Cruz', cp: '9300' },
    { nombre: 'Río Gallegos', cp: '9400' },
    { nombre: 'Río Turbio', cp: '9407' },
  ],

  'Santa Fe': [
    { nombre: 'Armstrong', cp: '2508' },
    { nombre: 'Cañada de Gómez', cp: '2500' },
    { nombre: 'Casilda', cp: '2170' },
    { nombre: 'Esperanza', cp: '3080' },
    { nombre: 'Firmat', cp: '2630' },
    { nombre: 'Frontera', cp: '2438' },
    { nombre: 'Rafaela', cp: '2300' },
    { nombre: 'Reconquista', cp: '3560' },
    { nombre: 'Rosario', cp: '2000' },
    { nombre: 'San Jorge', cp: '2452' },
    { nombre: 'San Lorenzo', cp: '2200' },
    { nombre: 'Santa Fe Capital', cp: '3000' },
    { nombre: 'Santo Tomé', cp: '3016' },
    { nombre: 'Sunchales', cp: '2322' },
    { nombre: 'Venado Tuerto', cp: '2600' },
    { nombre: 'Villa Constitución', cp: '2919' },
    { nombre: 'Villa Gobernador Gálvez', cp: '2124' },
  ],

  'Santiago del Estero': [
    { nombre: 'Añatuya', cp: '4260' },
    { nombre: 'Campo Gallo', cp: '4276' },
    { nombre: 'Clodomira', cp: '4206' },
    { nombre: 'Fernández', cp: '4204' },
    { nombre: 'Frías', cp: '4230' },
    { nombre: 'La Banda', cp: '4300' },
    { nombre: 'Las Termas de Río Hondo', cp: '4220' },
    { nombre: 'Loreto', cp: '4208' },
    { nombre: 'Monte Quemado', cp: '4280' },
    { nombre: 'Quimilí', cp: '4290' },
    { nombre: 'Santiago del Estero Capital', cp: '4200' },
    { nombre: 'Suncho Corral', cp: '4238' },
  ],

  'Tierra del Fuego': [
    { nombre: 'Río Grande', cp: '9420' },
    { nombre: 'Tolhuin', cp: '9412' },
    { nombre: 'Ushuaia', cp: '9410' },
  ],

  'Tucumán': [
    { nombre: 'Acheral', cp: '4134' },
    { nombre: 'Aguilares', cp: '4152' },
    { nombre: 'Alderetes', cp: '4101' },
    { nombre: 'Banda del Río Salí', cp: '4109' },
    { nombre: 'Bella Vista', cp: '4168' },
    { nombre: 'Burruyacú', cp: '4118' },
    { nombre: 'Concepción', cp: '4146' },
    { nombre: 'El Manantial', cp: '4105' },
    { nombre: 'Famaillá', cp: '4132' },
    { nombre: 'Graneros', cp: '4164' },
    { nombre: 'Juan Bautista Alberdi', cp: '4158' },
    { nombre: 'La Cocha', cp: '4162' },
    { nombre: 'Las Talitas', cp: '4101' },
    { nombre: 'Lules', cp: '4128' },
    { nombre: 'Monteros', cp: '4142' },
    { nombre: 'Ranchillos', cp: '4111' },
    { nombre: 'San Miguel de Tucumán', cp: '4000' },
    { nombre: 'San Pablo', cp: '4109' },
    { nombre: 'Simoca', cp: '4140' },
    { nombre: 'Tafí del Valle', cp: '4137' },
    { nombre: 'Tafí Viejo', cp: '4103' },
    { nombre: 'Trancas', cp: '4124' },
    { nombre: 'Yerba Buena', cp: '4107' },
  ],
};
